version: 2
executorType: docker
containerInfo:
  - image: markfirmware/ultibo-1.3.271-x64-1.0.0
stages:
  build:
    workDir: ~/ultibo-scout
    steps:
      - type: checkout
      - name: Build and test
        type: shell
        command: ./docker-build.sh
      - name: Save artifacts
        type: artifacts-store
        path: index.html
        destination: artifacts-browser.html
